name: GTAStyleTeleport
version: 1.5
main: com.ericlam.main.GTAStyleTP
author: hydranapse_
api-version: 1.13
commands:
  setloc:
    description: set test location
  loc:
    description: tp to test location
  return:
    description: restore player