name: AnimatedTeleport
version: "2.5"
main: com.ericlam.main.AnimatedTeleport
author: hydranapse_
api-version: "1.13"
commands:
  setloc:
    description: set test location
  loc:
    description: tp to test location
  ar-reload:
    aliases: [areload]
    description: reload config
permissions:
  ar.tester:
    default: op
    description: allow to use /setloc and /loc permissions
  ar.join:
    default: false
    description: allow player use this teleport when join
  ar.reload:
    default: op
    description: permission to reload config